module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts

params:
  persons:
    publications_persons:
      desktop: "50x50"
      mobile: "50x50"

# Default
permalinks:
  publications_persons: /publications/persons-concerned/:slug/
taxonomies:
  publications_person: publications_persons